# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Onlooker < Formula
  desc "Local observability agent for Claude Code"
  homepage "https://onlooker.dev"
  version "1.4.0"
  license "BlueOak-1.0.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/onlooker-community/onlooker/releases/download/v1.4.0/onlooker_darwin_amd64.tar.gz"
      sha256 "0fc3fc021cb6438c40aa9d6d98fa382e7d7c62affabae0b0e839f0e205cc8e2d"

      define_method(:install) do
        bin.install "onlooker"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/onlooker-community/onlooker/releases/download/v1.4.0/onlooker_darwin_arm64.tar.gz"
      sha256 "17ed3c52637544a4088c052718457824e708e9245da35d610c6864f3e3f09a0e"

      define_method(:install) do
        bin.install "onlooker"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/onlooker-community/onlooker/releases/download/v1.4.0/onlooker_linux_amd64.tar.gz"
      sha256 "55ccd3d9d6613e38cd1f2ba3dc1926de2a5aaf3801310c51efc1187303eac7a8"
      define_method(:install) do
        bin.install "onlooker"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/onlooker-community/onlooker/releases/download/v1.4.0/onlooker_linux_arm64.tar.gz"
      sha256 "1b6bee29c8ce53f4767c3c568a1a06659d4737b542524062b7d1551d3107992d"
      define_method(:install) do
        bin.install "onlooker"
      end
    end
  end

  def caveats
    <<~EOS
      To get started, link this machine to your Onlooker account:

        onlooker link

      Then start the background agent (or let Homebrew manage it):

        onlooker daemon
        brew services start onlooker

      Config: ~/.config/onlooker/config.toml
      Docs:   https://onlooker.dev/docs
    EOS
  end

  service do
    run [opt_bin/"onlooker", "daemon"]
    keep_alive true
    log_path var/"log/onlooker.log"
    error_log_path var/"log/onlooker.log"
    environment_variables PATH: std_service_path_env
  end

  test do
    system "#{bin}/onlooker", "version"
  end
end
