# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Onlooker < Formula
  desc "Local observability agent for Claude Code"
  homepage "https://onlooker.dev"
  version "1.10.0"
  license "BlueOak-1.0.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/onlooker-community/onlooker/releases/download/v1.10.0/onlooker_darwin_amd64.tar.gz"
      sha256 "b18380138fb4baebb09fddfdcd9196886c0cbafff6151c5a9eb5bd79982d410a"

      define_method(:install) do
        bin.install "onlooker"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/onlooker-community/onlooker/releases/download/v1.10.0/onlooker_darwin_arm64.tar.gz"
      sha256 "0279ceaf6bbac422c8035d3913ef845e75291870f89c226d99c6e09f2f051c01"

      define_method(:install) do
        bin.install "onlooker"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/onlooker-community/onlooker/releases/download/v1.10.0/onlooker_linux_amd64.tar.gz"
      sha256 "ab12af0f025cbc932b524a56974fc0f19267e6f358a22f28ac37f44abfddafb2"
      define_method(:install) do
        bin.install "onlooker"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/onlooker-community/onlooker/releases/download/v1.10.0/onlooker_linux_arm64.tar.gz"
      sha256 "5c7ab1245576e3c696ce55594e7ba3f6ed9412a044d7d7d5dd112bea16597282"
      define_method(:install) do
        bin.install "onlooker"
      end
    end
  end

  def caveats
    <<~EOS
      To get started, link this machine to your Onlooker account:

        onlooker link

      Then start the background agent (or let Homebrew manage it):

        onlooker daemon
        brew services start onlooker

      Config: ~/.config/onlooker/config.toml
      Docs:   https://onlooker.dev/docs
    EOS
  end

  service do
    run [opt_bin/"onlooker", "daemon"]
    keep_alive true
    log_path var/"log/onlooker.log"
    error_log_path var/"log/onlooker.log"
    environment_variables PATH: std_service_path_env
  end

  test do
    system "#{bin}/onlooker", "version"
  end
end
